config/routes.rb
Rails.application.routes.draw do

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :new, :show, :create, :show, :edit, :update]
    resources :workers, only: [:index, :show, :edit, :update]
    resources :progresses, only: [:index, :show]
  end

  #従業員用
  devise_for :worker,skip: [:passwords], controllers: {
    registrations: "worker/registrations",
    sessions: 'worker/sessions'
  }
  scope module: :worker do
    root to: 'products#index'
    resources :workers, only: [:index, :show, :edit, :update]
    resources :products, only: [:index, :show]
    resources :progresses, only: [:index, :show, :create]

    post 'progresses/start' => 'progresses#start' #商品開始
    post 'progresses/finish' => 'progresses#finish' #商品終了
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :progresses, dependent: :destroy
  belongs_to :genre

  validates :genre_id, presence: true
  validates :product_count, presence: true
  validates :delivery_date, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @product = Product.new
    @genres = Genre.all
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to admin_products_path, notice: "商品 #{@product.genre.name} を登録しました。"
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @genres = Genre.all
  end

  def update
    @product = Product.find(params[:id])
    @product.update(products_params)
    redirect_to admin_product_path
  end

  private

  def products_params
    params.require(:product).permit(:genre_id, :delivery_date, :product_count)
  end
end

app/controllers/worker/products_controller.rb
class Worker::ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @new_progress = Progress.new
    @progress = Progress.find_by(product_id: @product.id)
    #@progress = Progress.find_by(product_id: @product.id, end_time: nil)
  end

  private

  def progress_params
    params.require(:progress).permit(:product_id, :worker_id, :progress_status, :begin_time, :end_time)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/worker/products_helper.rb
module Worker::ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
  <%= form_with model: [:admin,@product] do |f| %>
    <div class="row">
      <h3 class="m-3 bg-light">商品情報更新</h3>
    </div>

    <div class="field row">
      <div class="col-2"><%= f.label :genre_id,"商品名" %></div>
      <div class="col-6">
        <%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "ジャンルを選択してください"}, {class: "form-control mb-2"}) %>
      </div>
    </div>

    <div class="field row">
      <div class="col-2"><%= f.label :product_count,"数量" %></div>
      <div class="col-4">
        <%= f.text_field :product_count, class: "form-control mb-2",placeholder: "例）1000" %>
      </div>
    </div>

    <div class="genre field row">
      <div class="col-2"><%= f.label :delivery_date,"納期" %></div>
      <div class="col-6">
        <%= f.date_select :delivery_date, {}, class: 'form-control' %>
      </div>
    </div>

    <div class="row my-5">
      <div class="col-2"></div>
      <div class="col-6 form-inline">
        <div class="mr-5">
          <%= f.submit "更新", class: "btn btn-success" %>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="my-5 bg-light">商品一覧</h3>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-10">

      <div class="row">
        <%= link_to new_admin_product_path, class: "text-dark mb-2" do %>
          <i class="fas fa-plus"></i> 商品新規登録
        <%end%>
      </div>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>数量</th>
            <th>納期</th>
            <th></th>
          </tr>
        </thead>
        <% @products.each do |product| %>
        <tbody>
          <tr>
            <td><%= product.id %></td>
            <td>
              <%= link_to product.genre.name, admin_product_path(product.id) %>
            </td>
            <td><%= product.product_count.to_s(:delimited) %></td>
            <td><%= product.delivery_date %></td>
            <td>
              <%= link_to '編集する', edit_admin_product_path(product.id), class: "btn btn-success" %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
  <%#= paginate @products %>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <%= form_with model: [:admin,@product] do |f| %>
    <div class="row">
      <h3 class="m-3 bg-light">商品新規登録</h3>
    </div>

    <div class="field row">
      <div class="col-2"><%= f.label :genre_id,"商品名" %></div>
      <div class="col-6">
        <%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "ジャンルを選択してください"}, {class: "form-control mb-2"}) %>
      </div>
    </div>

    <div class="field row">
      <div class="col-2"><%= f.label :product_count,"数量" %></div>
      <div class="col-4">
        <%= f.text_field :product_count, class: "form-control mb-2",placeholder: "例）1000" %>
      </div>
    </div>

    <div class="genre field row">
      <div class="col-2"><%= f.label :delivery_date,"納期" %></div>
      <div class="col-6">
        <%= f.date_select :delivery_date, {}, class: 'form-control' %>
      </div>
    </div>

    <div class="row my-5">
      <div class="col-2"></div>
      <div class="col-6 form-inline">
        <div class="mr-5">
          <%= f.submit "新規登録", class: "btn btn-success" %>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/admin/products/show.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <h3 class="bg-light">商品詳細</h3>
  </div>
  <div class="row">

      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>商品ID</td>
            <td><%= @product.id %></td>
          </tr>
          <tr>
            <td>商品名</td>
            <td><%= @product.genre.name%></td>
          </tr>
          <tr>
            <td>数量</td>
            <td><%= @product.product_count %></td>
          </tr>
          <tr>
            <td>納期</td>
            <td><%= @product.delivery_date %></td>
          </tr>
        </tbody>
      </table>
      <%= link_to '編集する', edit_admin_product_path(@product.id), class: "btn btn-success" %>
    </div>
  </div>
</div>