config/routes.rb
Rails.application.routes.draw do

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :new, :show, :create, :show, :edit, :update]
    resources :workers, only: [:index, :show, :edit, :update]
    resources :progresses, only: [:index, :show]
  end

  #従業員用
  devise_for :worker,skip: [:passwords], controllers: {
    registrations: "worker/registrations",
    sessions: 'worker/sessions'
  }
  scope module: :worker do
    root to: 'products#index'
    resources :workers, only: [:index, :show, :edit, :update]
    resources :products, only: [:index, :show]
    resources :progresses, only: [:index, :show, :create]

    post 'progresses/start' => 'progresses#start' #商品開始
    post 'progresses/finish' => 'progresses#finish' #商品終了
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :progresses, dependent: :destroy
  belongs_to :genre

  validates :genre_id, presence: true
  validates :product_count, presence: true
  validates :delivery_date, presence: true
end

app/models/progress.rb
class Progress < ApplicationRecord
  belongs_to :worker
  belongs_to :product

  enum progress_status: { waiting: 0, phase_one: 1, phase_two: 2, phase_three: 3, phase_four: 4, finish: 5 }
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :progresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
  def active_for_authentication?
    super && (is_deleted == false)
  end  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.page(params[:page])
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.page(params[:page])
    if @genre.save
      flash.now[:notice] = "ジャンルを登録しました"
    else
      @genres = Genre.page(params[:page])
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @product = Product.new
    @genres = Genre.all
  end

  def create
    @product = Product.new(products_params)
    if @product.save
      redirect_to admin_products_path, notice: "商品 #{@product.genre.name} を登録しました。"
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @genres = Genre.all
  end

  def update
    @product = Product.find(params[:id])
    @product.update(products_params)
    redirect_to admin_product_path
  end

  private

  def products_params
    params.require(:product).permit(:genre_id, :delivery_date, :product_count)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    admin_progresses_path
  end

  def after_sign_out_path_for(resource)
    admin_session_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/workers_controller.rb
class Admin::WorkersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @workers = Worker.all
  end

  def show
    @worker = Worker.find(params[:id])
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  def update
    @worker = Worker.find(params[:id])
    @worker.update(workers_params)
    flash[:notice] = "顧客情報を更新しました。"
    redirect_to admin_worker_path(@worker)
  end

  private

  def workers_params
    params.require(:worker).permit(:first_name, :last_name, :email, :is_deleted)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/progress_helper.rb
module Admin::ProgressHelper
end

app/helpers/admin/workers_helper.rb
module Admin::WorkersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/worker/products_helper.rb
module Worker::ProductsHelper
end

app/helpers/worker/progresses_helper.rb
module Worker::ProgressesHelper
end

app/helpers/worker/workers_helper.rb
module Worker::WorkersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success shadow-sm">
    <div class="container">

      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" >
            <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_progresses_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-list"></i> 進捗状況
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_products_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-users"></i> 商品一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_genres_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-history"></i> ジャンル一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_workers_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-layer-group"></i> 従業員一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>
          <% elsif worker_signed_in? %>
            <p class="text-white mr-2 my-auto text-nowrap"><small></small><%= current_worker.last_name %><%= current_worker.first_name %><small></small></p>
            <li class="nav-item">
              <%= link_to worker_path(current_worker.id), class: "nav-link text-light text-nowrap btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-user-circle"></i> マイページ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to progresses_path, class: "nav-link text-light text-nowrap btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-list"></i> 進捗状況
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to products_path, class: "nav-link text-light text-nowrap btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-shopping-cart"></i> 商品一覧
              <% end %>
            </li>
              <li class="nav-item">
              <%= link_to workers_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-layer-group"></i> 従業員一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_worker_session_path, method: :delete, class:"nav-link text-light text-nowrap btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%#= link_to about_path, class: "nav-link text-light btn btn-primary mr-1 mb-1" do %>
                <!--<i class="fas fa-link"></i> About-->
              <%# end %>
            </li>
            <li class="nav-item">
              <%= link_to products_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-list"></i> 商品一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_worker_registration_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-user-plus"></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_worker_session_path, class: "nav-link text-light btn btn-outline-success mr-1 mb-1" do %>
                <i class="fas fa-sign-in-alt"></i> ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
        <!--<div>-->
          <%#= search_form_for @search, url: products_path do |f| %>
            <%#= f.text_field :name_cont %>
            <%#= f.submit "検索" %>
          <%# end %>
          <!--<form class="d-flex">-->
          <!--  <input class="form-control mr-2 mb-1" type="search" placeholder="Search" aria-label="Search">-->
          <!--  <button class="btn btn-outline-success mb-1" type="submit">Search</button>-->
          <!--</form>-->
        </div>
      </div>
    </div>
  </nav>

app/views/layouts/_notice.html.erb
<% if notice %>
 <p id="notice" class="alert alert-warning m-0 text-center"><%= notice %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgressApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <hearder>
      <%= render 'layouts/header' %>
    </hearder>

    <main>
       <div id="flash-success">
        <%=render "layouts/notice" %>
      </div>
      <%= yield %>
    </main>

    <footer>
      <div class="py-4 bg-success text-center">
        <div class="container">
          <i class="fab fa-twitter text-white-50"></i>
          <i class="fab fa-instagram text-white-50"></i>
          <i class="fab fa-facebook text-white-50"></i>
          <p class="text-white small">&copy; 2022 Daichi Taguchi</p>
        </div>
      </div>
    </footer>

  </body>

</html>