config/routes.rb
Rails.application.routes.draw do

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :products, only: [:index, :new, :show, :create, :show, :edit, :update]
    resources :workers, only: [:index, :show, :edit, :update]
    resources :progresses, only: [:index, :show]
  end

  #従業員用
  devise_for :worker,skip: [:passwords], controllers: {
    registrations: "worker/registrations",
    sessions: 'worker/sessions'
  }
  scope module: :worker do
    root to: 'products#index'
    resources :workers, only: [:index, :show, :edit, :update]
    resources :products, only: [:index, :show]
    resources :progresses, only: [:index, :show, :create]

    post 'progresses/start' => 'progresses#start' #商品開始
    post 'progresses/finish' => 'progresses#finish' #商品終了
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :progresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
  def active_for_authentication?
    super && (is_deleted == false)
  end  
end

app/controllers/admin/workers_controller.rb
class Admin::WorkersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @workers = Worker.all
  end

  def show
    @worker = Worker.find(params[:id])
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  def update
    @worker = Worker.find(params[:id])
    @worker.update(workers_params)
    flash[:notice] = "顧客情報を更新しました。"
    redirect_to admin_worker_path(@worker)
  end

  private

  def workers_params
    params.require(:worker).permit(:first_name, :last_name, :email, :is_deleted)
  end

end

app/controllers/worker/confirmations_controller.rb
# frozen_string_literal: true

class Worker::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/worker/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Worker::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/worker/passwords_controller.rb
# frozen_string_literal: true

class Worker::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/worker/products_controller.rb
class Worker::ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @new_progress = Progress.new
    @progress = Progress.find_by(product_id: @product.id)
    #@progress = Progress.find_by(product_id: @product.id, end_time: nil)
  end

  private

  def progress_params
    params.require(:progress).permit(:product_id, :worker_id, :progress_status, :begin_time, :end_time)
  end
end

app/controllers/worker/progresses_controller.rb
class Worker::ProgressesController < ApplicationController
  before_action :authenticate_worker!

  def index
    #@progresses = worker.progress
  end

  def show
    #@progress = current_worker.progress
  end

  def start
    @progress = Progress.new
    @progress.product_id = params[:progress][:product_id]
    @progress.worker_id = current_worker.id
    @progress.begin_time = DateTime.now
    @progress.save!
    redirect_to product_path(@progress.product_id)
  end

  def finish
    @progress = Progress.find(params[:progress][:id])
    @progress.end_time = DateTime.now
    @progress.save!
    redirect_to products_path
  end

  private

  def progress_params
    params.require(:progress).permit(:product_id, :worker_id, :progress_status, :begin_time, :end_time)
  end
end

app/controllers/worker/registrations_controller.rb
# frozen_string_literal: true

class Worker::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    progresses_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name])
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/worker/sessions_controller.rb
# frozen_string_literal: true

class Worker::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    progresses_path
  end

  def after_sign_out_path_for(resource)
    new_worker_session_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/worker/unlocks_controller.rb
# frozen_string_literal: true

class Worker::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/worker/workers_controller.rb
class Worker::WorkersController < ApplicationController
  
  def index
    @workers = Worker.all
  end

  def show
    @worker = Worker.find(params[:id])
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  def update
    @worker = Worker.find(params[:id])
    @worker.update(workers_params)
    redirect_to worker_path(params[:id])
  end

  private

  def workers_params
    params.require(:worker).permit(:first_name, :last_name, :email)
  end

end

app/helpers/admin/workers_helper.rb
module Admin::WorkersHelper
end

app/helpers/worker/products_helper.rb
module Worker::ProductsHelper
end

app/helpers/worker/progresses_helper.rb
module Worker::ProgressesHelper
end

app/helpers/worker/workers_helper.rb
module Worker::WorkersHelper
end

app/views/worker/workers/_info.html.erb
<table class ="table">
  <tbody>
    <tr>
      <td>従業員名</td>
      <td><%= worker.last_name %>　<%= worker.first_name %></td>
    </tr>
    <tr>
      <td>ID</td>
      <td><%= worker.id %></td>
    </tr>
    <tr>
      <td>平均部数(/h)</td>
      <td></td>
    </tr>
    <tr>
      <td>最大部数(/day)</td>
      <td></td>
    </tr>
    <tr>
      <td>月間件数</td>
      <td></td>
    </tr>
  </tbody>
</table>

<div class='row'>
    <% if current_worker != worker %>
      <td><%#= render "relationships/btn", user: user %></td>
    <% else %>
      <%= link_to  edit_worker_path(worker), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <%end%>
    <%end%>
    <td>
      <%# if current_user != user && current_user.following?(user) && user.following?(current_user) %>
        <%#= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
      <%# end %>
    </td>

  </div>

app/views/worker/workers/edit.html.erb
<div class="container">
  <%= form_with model: @worker do |f| %>
    <div class="row">
      <h3 class="m-3 bg-light">従業員情報更新</h3>
    </div>

    <div class="field row mb-3">
      <div class="col-3"><%= f.label :name, "名前" %></div>
      <div class="col-6 form-inline">
        <%= f.label :last_name, "(姓)", class: "pr-2" %>
        <%= f.text_field :last_name, autofocus: true, class: "form-control mr-2" %>
        <%= f.label :first_name, "(名)", class: "pr-2" %>
        <%= f.text_field :first_name, class: "form-control mr-2" %>
      </div>
    </div>
    
    <div class="field row mb-3">
      <div class="col-3"><%= f.label :email, "メールアドレス" %></div>
      <div class="col-6"><%= f.email_field :email, autocomplete: "email", class: "form-control" %></div>
    </div>

    <!--<div class="field row mb-3">-->
    <!--  <div class="col-3"><%#= f.label :password, "パスワード(6文字以上)" %></div>-->
    <!--  <div class="col-6"><%#= f.password_field :password, autocomplete: "new-password", class: "form-control" %></div>-->
    <!--</div>-->

    <!--<div class="field row mb-3">-->
    <!--  <div class="col-3"><%#= f.label :password_confirmation, "パスワード(確認用)" %></div>-->
    <!--  <div class="col-6"><%#= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %></div>-->
    <!--</div>-->
    
    <div class="row my-5">
      <div class="col-2"></div>
      <div class="col-6 form-inline">
        <div class="mr-5">
          <%= f.submit "更新", class: "btn btn-success" %>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/worker/workers/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="my-5 bg-light">従業員一覧</h3>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-10">

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>ID</th>
            <th>名前</th>
            <th></th>
          </tr>
        </thead>
        <% @workers.each do |worker| %>
        <tbody>
          <tr>
            <td><%= worker.id %></td>
            <td>
              <%= link_to worker_path(worker.id) do%>
                <%= worker.last_name %> <%= worker.first_name %>
              <%end%>
            </td>
            <td>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
  <%#= paginate @products %>
</div>

app/views/worker/workers/show.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
    <div class='col-md-3'>
      <h2>従業員詳細</h2>
      <%= render 'info', worker: @worker %>
    </div>

    <div class='col-md-8 offset-md-1'>

    </div>
  </div>
</div>